T-5280[ADD]sale_disable_cancel_warning
sygel-technology/sy-sale-workflow pull request #24
Opened 2023-12-15 13:47 UTC by Tisho99

2023-12-19 12:01 UTC, ValentinVinagre requested changes
Algunos comentarios

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/README.rst
> +#. Go to Settings / Sales / Quotations & Orders and mark/unmark the Disable Cancel Warning option
no sería sales/settings?

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/models/sale_order.py
> +        if self.env['ir.config_parameter'].sudo().get_param(
¿Lo has probado que funcione en multicompañía con diferentes opciones en las compañias? (1 activa y otra no, etc)

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/views/res_config_settings.xml
> +    <record id="res_config_settings_view_form" model="ir.ui.view">
indica un ID más apropiado

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/views/res_config_settings.xml
> +        <field name="name">res.config.settings.view.form.inherit.sale.disable.cancel.warning</field>
intenta reducir un poco el name

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/views/res_config_settings.xml
> +</odoo>
te falta un salto de carro final

2023-12-19 12:01 UTC, ValentinVinagre commented on sale_disable_cancel_warning/README.rst
> +[ Enumerate known caveats and future potential improvements.
elimina la parte entre [] es como un comentario

2023-12-19 15:46 UTC, Tisho99 commented on sale_disable_cancel_warning/models/sale_order.py
> +        if self.env['ir.config_parameter'].sudo().get_param(
Lo acabo de probar y la opción no depende de la compañia, o todas tendrán warning, o ninguna.

¿Es necesario que se pueda configurar el warning dependiendo de la compañia?

2023-12-19 15:52 UTC, ValentinVinagre commented on sale_disable_cancel_warning/models/sale_order.py
> +        if self.env['ir.config_parameter'].sudo().get_param(
es posible que alguna compañía si lo necesite y lo quiera utilizar, hay que respetar estos posibles cambios de "funcionalidades" entre compañías.

2023-12-21 15:47 UTC, ValentinVinagre approved these changes

2023-12-21 15:47 UTC, merged