[T-6543][17.0][MIG+IMP] queued_sale_notify: migration + refactor
sygel-technology/sy-sale-workflow pull request #48
Opened 2024-10-08 13:26 UTC by Tisho99

2024-10-10 10:35 UTC, Tisho99 commented
@ValentinVinagre @HaraldPanten @luis-ron 

The PR is ready

2024-10-11 14:00 UTC, HaraldPanten commented
Don't you need to check tests?

2024-10-14 07:03 UTC, Tisho99 commented
@HaraldPanten 

No, that check if failing because i added a test-requierments.txt file in a "DON'T MERGE" commit with the dependencies of other PR. When the base module is merged, i will remove that commit and everything will be ocay

2024-10-16 15:11 UTC, HaraldPanten commented
@Tisho99 OK then. Let's wait for other reviewers

2024-10-22 09:50 UTC, luis-ron approved these changes
Functional review: LGTM 👍🏻

2024-10-24 09:22 UTC, manuelregidor requested changes
Also, either credit me or remove my name from files.

2024-10-24 09:22 UTC, manuelregidor commented on queued_sale_notify/models/sale_notify_mixin.py
> +        return self.trigger_state == "sale" and record.state == "sale"
Shouldn't done state be considered?

2024-10-24 09:22 UTC, manuelregidor commented on queued_sale_notify/models/sale_order.py
> +                    if notify_id.is_to_notify(rec):
Couldn't you get rid of this check? It checked again when notify is called.

2024-10-29 12:45 UTC, Tisho99 commented on queued_sale_notify/models/sale_notify_mixin.py
> +        return self.trigger_state == "sale" and record.state == "sale"
There is no done state in v17

2024-10-29 13:31 UTC, manuelregidor commented
Technical review. LGTM

2024-10-29 13:31 UTC, manuelregidor approved these changes

2024-10-30 11:59 UTC, merged