[T-7197][16.0][FIX] sale_stock_deposit: stock -> deposit rule right operation
sygel-technology/sy-sale-workflow pull request #55
Opened 2024-12-30 08:26 UTC by manuelregidor

@HaraldPanten @ValentinVinagre 
@Jaimermaccione Could you review?

2024-12-30 08:56 UTC, ValentinVinagre reviewed
LGTM 👍🏻

2024-12-30 08:56 UTC, ValentinVinagre approved these changes

2025-01-02 09:20 UTC, Jaimermaccione commented
@manuelregidor Perfect, Manu. It’s now working correctly by assigning the delivery operation type in the route rule.

However, I noticed one more thing: the operation type, in the warehouse field, is created for the main warehouse by default. To reproduce this, try creating a new warehouse in the environment (when there is already at least one existing warehouse) and check the warehouse assigned to the operation types. This happens for both sales and deposit delivery operations.

I don’t think this has any practical implications for now, but it’s better to have everything properly defined. Let me know what you think.

Thanks!

2025-01-02 10:03 UTC, Jaimermaccione requested changes
It’s now working correctly by assigning the delivery operation type in the route rule.

However, I noticed one more thing: the operation type, in the warehouse field, is created for the main warehouse by default. To reproduce this, try creating a new warehouse in the environment (when there is already at least one existing warehouse) and check the warehouse assigned to the operation types. This happens for both sales and deposit delivery operations.

I don’t think this has any practical implications for now, but it’s better to have everything properly defined. Let me know what you think.

Thanks!

2025-01-02 13:22 UTC, manuelregidor commented
@Jaimermaccione Could you check again? Thank you!

2025-01-02 13:30 UTC, Jaimermaccione approved these changes
LGTM!

2025-01-03 08:59 UTC, ValentinVinagre commented
/sygelbot merge minor

2025-01-03 09:07 UTC, ValentinVinagre commented
​/sygelbot rebase

2025-01-03 09:07 UTC, ValentinVinagre commented
@manuelregidor review the conflict please 👍🏻

2025-01-03 12:15 UTC, ValentinVinagre commented
/sygelbot merge minor

2025-01-03 12:18 UTC, merged