[T-6942][ADD] sale_order_invoicing_picking_filter_groping_criteria: Glue module
sygel-technology/sy-sale-workflow pull request #56
Opened 2024-12-30 16:06 UTC by Tisho99

New glue module between sale_order_invoicing_picking_filter and sale_order_invoicing_groping_criteria

2025-01-02 08:36 UTC, Jaimermaccione approved these changes
@Tisho99 LGTM! Tested its functionality in a local environment. Just one tiny detail: the technical name should be "grouping" instead of "groping".

2025-01-02 09:57 UTC, Jaimermaccione requested changes
@Tisho99 Just one tiny detail: the technical name should be "grouping" instead of "groping".

2025-01-02 10:13 UTC, Tisho99 commented
@Jaimermaccione 

The changes are applied, can you approbe the PR?

2025-01-02 10:17 UTC, Jaimermaccione approved these changes
LGTM! Tested its functionality in a local environment.

2025-01-02 15:35 UTC, manuelregidor approved these changes
Technical review. LGTM

2025-01-02 16:30 UTC, Tisho99 commented
@ValentinVinagre can you merge?

2025-01-02 16:30 UTC, Tisho99 commented
@ValentinVinagre Will Manu have permissions to merge??

2025-01-03 08:58 UTC, ValentinVinagre commented
/sygelbot merge nobump

2025-01-03 09:02 UTC, merged